export default [ 
    { id: 1, text: 'Would you ever kiss on the first date?', uri: require('./assets/1.jpg') },
    { id: 2, text: 'Would you hook up with someone on the first date?', uri: require('./assets/2.jpg')  },
    { id: 3, text: 'Would you ever date your ex?', uri: require('./assets/3.jpg')  },
    { id: 4, text: 'Would you ever talk to your best friend\'s ex?', uri: require('./assets/4.jpg')  },
    { id: 5, text: 'Would you ever date someone who is older than you?', uri: require('./assets/1.jpg') },
    { id: 6, text: 'Would you ever date someone who is younger than you?', uri: require('./assets/2.jpg')  },
    { id: 7, text: 'Would you ever stay friends with your ex?', uri: require('./assets/3.jpg')  },
    { id: 8, text: 'Would you ever lie to your significant other to keep from hurting their feelings?', uri: require('./assets/4.jpg')  },
    { id: 9, text: 'Would you ever get back with an ex who cheated on you?', uri: require('./assets/4.jpg')  },
    { id: 10, text: 'Would you ever tell someone you love them, even though you don\'t?', uri: require('./assets/4.jpg')  },
    { id: 11, text: 'Do you believe in true love?', uri: require('./assets/1.jpg') },
    { id: 12, text: 'Does your life have meaning?', uri: require('./assets/2.jpg')  },
    { id: 13, text: 'What would you want your final words to be?', uri: require('./assets/3.jpg')  },
    { id: 14, text: 'What impression do you think you give when you first meet someone?', uri: require('./assets/4.jpg')  },
    { id: 15, text: 'If you had the chance to know when and how you\'d die, would you take it?', uri: require('./assets/1.jpg') },
    { id: 16, text: 'Do you believe in heaven & hell?', uri: require('./assets/2.jpg')  },
    { id: 17, text: 'Things that irritate you about the opposite/same sex?', uri: require('./assets/3.jpg')  },
    { id: 18, text: 'Story of first kiss?', uri: require('./assets/4.jpg')  },
    { id: 19, text: 'Something you regret?', uri: require('./assets/4.jpg')  },
    { id: 20, text: 'What do you find funny that other people don\'t?', uri: require('./assets/4.jpg')  },
    { id: 21, text: 'If you could have one superpower, what would it be?', uri: require('./assets/1.jpg') },
    { id: 22, text: '3 words that best describe you?', uri: require('./assets/2.jpg')  },
    { id: 23, text: 'What feature of mine do you find most attractive?', uri: require('./assets/3.jpg')  },
    { id: 24, text: 'How old were you when you had your first kiss?', uri: require('./assets/4.jpg')  },
    { id: 25, text: 'Would you ever date someone who is older than you?', uri: require('./assets/1.jpg') },
    { id: 26, text: 'Would you ever date someone who is younger than you?', uri: require('./assets/2.jpg')  },
    { id: 27, text: 'Would you ever stay friends with your ex?', uri: require('./assets/3.jpg')  },
    { id: 28, text: 'Would you ever lie to your significant other to keep from hurting their feelings?', uri: require('./assets/4.jpg')  },
    { id: 29, text: 'Would you ever get back with an ex who cheated on you?', uri: require('./assets/4.jpg')  },
    { id: 30, text: 'Would you ever tell someone you love them, even though you don\'t?', uri: require('./assets/4.jpg')  },
  ];