// export default [ 
//     { id: 1, text: 'Would you ever kiss on the first date?', uri: require('./assets/1.jpg') },
//     { id: 2, text: 'Would you hook up with someone on the first date?', uri: require('./assets/2.jpg')  },
//     { id: 3, text: 'Would you ever date your ex?', uri: require('./assets/3.jpg')  },
//     { id: 4, text: 'Would you ever talk to your best friend\'s ex?', uri: require('./assets/4.jpg')  },
//     { id: 5, text: 'Would you ever date someone who is older than you?', uri: require('./assets/1.jpg') },
//     { id: 6, text: 'Would you ever date someone who is younger than you?', uri: require('./assets/2.jpg')  },
//     { id: 7, text: 'Would you ever stay friends with your ex?', uri: require('./assets/3.jpg')  },
//     { id: 8, text: 'Would you ever lie to your significant other to keep from hurting their feelings?', uri: require('./assets/4.jpg')  },
//     { id: 9, text: 'Would you ever get back with an ex who cheated on you?', uri: require('./assets/4.jpg')  },
//     { id: 10, text: 'Would you ever tell someone you love them, even though you don\'t?', uri: require('./assets/4.jpg')  },
//     { id: 11, text: 'Do you believe in true love?', uri: require('./assets/1.jpg') },
//     { id: 12, text: 'Does your life have meaning?', uri: require('./assets/2.jpg')  },
//     { id: 13, text: 'What would you want your final words to be?', uri: require('./assets/3.jpg')  },
//     { id: 14, text: 'What impression do you think you give when you first meet someone?', uri: require('./assets/4.jpg')  },
//     { id: 15, text: 'If you had the chance to know when and how you\'d die, would you take it?', uri: require('./assets/1.jpg') },
//     { id: 16, text: 'Do you believe in heaven & hell?', uri: require('./assets/2.jpg')  },
//     { id: 17, text: 'Things that irritate you about the opposite/same sex?', uri: require('./assets/3.jpg')  },
//     { id: 18, text: 'Story of first kiss?', uri: require('./assets/4.jpg')  },
//     { id: 19, text: 'Something you regret?', uri: require('./assets/4.jpg')  },
//     { id: 20, text: 'What do you find funny that other people don\'t?', uri: require('./assets/4.jpg')  },
//     { id: 21, text: 'If you could have one superpower, what would it be?', uri: require('./assets/1.jpg') },
//     { id: 22, text: '3 words that best describe you?', uri: require('./assets/2.jpg')  },
//     { id: 23, text: 'What feature of mine do you find most attractive?', uri: require('./assets/3.jpg')  },
//     { id: 24, text: 'How old were you when you had your first kiss?', uri: require('./assets/4.jpg')  },
//     { id: 25, text: 'Would you ever date someone who is older than you?', uri: require('./assets/1.jpg') },
//     { id: 26, text: 'Would you ever date someone who is younger than you?', uri: require('./assets/2.jpg')  },
//     { id: 27, text: 'Would you ever stay friends with your ex?', uri: require('./assets/3.jpg')  },
//     { id: 28, text: 'Would you ever lie to your significant other to keep from hurting their feelings?', uri: require('./assets/4.jpg')  },
//     { id: 29, text: 'Would you ever get back with an ex who cheated on you?', uri: require('./assets/4.jpg')  },
//     { id: 30, text: 'Would you ever tell someone you love them, even though you don\'t?', uri: require('./assets/4.jpg')  },
//   ];

  export default [
    {'text': "Yo mama's so fat, when she fell I didn't laugh, but the sidewalk cracked up.\n", 'id': 0, 'uri': ''},
    {'text': "Yo mama's so fat, when she skips a meal, the stock market drops.\n", 'id': 1, 'uri': ''},
    // {'text': "Yo mama's so fat, it took me two buses and a train to get to her good side.\n", 'id': 2, 'uri': ''},
    // {'text': "Yo mama's so fat, when she goes camping, the bears hide their food.\n", 'id': 3, 'uri': ''},
    // {'text': "Yo mama's so fat, if she buys a fur coat, a whole species will become extinct.\n", 'id': 4, 'uri': ''},
    // {'text': 'Yo mama\'s so fat, she stepped on a scale and it said: "To be continued."\n', 'id': 5, 'uri': ''},
    // {'text': "Yo mama's so fat, I swerved to miss her in my car and ran out of gas.\n", 'id': 6, 'uri': ''},
    // {'text': "Yo mama's so fat, when she wears high heels, she strikes oil.\n", 'id': 7, 'uri': ''},
    // {'text': "Yo mama's so fat, she was overthrown by a small militia group, and now she's known as the Republic of Yo Mama.\n", 'id': 8, 'uri': ''},
    // {'text': "Yo mama's so fat, when she sits around the house, she SITS AROUND the house.\n", 'id': 9, 'uri': ''},
    // {'text': "Yo mama's so fat, her car has stretch marks.\n", 'id': 10, 'uri': ''},
    // {'text': "Yo mama's so fat, she can't even jump to a conclusion.\n", 'id': 11, 'uri': ''},
    // {'text': "Yo mama's so fat, her blood type is Ragu.\n", 'id': 12, 'uri': ''},
    // {'text': "Yo mama's so fat, if she was a Star Wars character, her name would be Admiral Snackbar.\n", 'id': 13, 'uri': ''},
    // {'text': "Yo mama's so fat, she brought a spoon to the Super Bowl.\n", 'id': 14, 'uri': ''},
    // {'text': 'Yo mama\'s so stupid, she stared at a cup of orange juice for 12 hours because it said "concentrate."\n', 'id': 15, 'uri': ''},
    // {'text': "Yo mama's so stupid when they said it was chilly outside, she grabbed a bowl.\n", 'id': 16, 'uri': ''},
    // {'text': "Yo mama's so stupid, she put lipstick on her forehead to make up her mind.\n", 'id': 17, 'uri': ''},
    // {'text': 'Yo mama\'s so stupid, when they said, "Order in the court," she asked for fries and a shake.\n', 'id': 18, 'uri': ''},
    // {'text': "Yo mama's so stupid, she thought a quarterback was a refund.\n", 'id': 19, 'uri': ''},
    // {'text': "Yo mama's so stupid, she thought a quarterback was a refund.\n", 'id': 20, 'uri': ''},
    // {'text': "Yo mama's so stupid, she got hit by a parked car.\n", 'id': 21, 'uri': ''},
    // {'text': "Yo mama's so stupid, when I told her that she lost her mind, she went looking for it\n", 'id': 22, 'uri': ''},
    // {'text': 'Yo mama\'s so stupid when thieves broke into her house and stole the TV, she chased after them shouting "Wait, you forgot the remote!"\n', 'id': 23, 'uri': ''},
    // {'text': "Yo mama's so stupid, she went to the dentist to get a Bluetooth.\n", 'id': 24, 'uri': ''},
    // {'text': "Yo mama's so stupid, she took a ruler to bed to see how long she slept.\n", 'id': 25, 'uri': ''},
    // {'text': "Yo mama's so stupid, she got locked in the grocery store and starved to death.\n", 'id': 26, 'uri': ''},
    // {'text': 'Yo mama\'s so stupid, when I said, "Drinks on the house," she got a ladder.\n', 'id': 27, 'uri': ''},
    // {'text': "Yo mama's so stupid, it takes her two hours to watch 60 Minutes.\n", 'id': 28, 'uri': ''},
    // {'text': "Yo mama's so stupid, she put airbags on her computer in case it crashed.\n", 'id': 29, 'uri': ''},
    // {'text': "Yo mama's so ugly, she threw a boomerang and it refused to come back.\n", 'id': 30, 'uri': ''},
    // {'text': "Yo mama's so old, her social security number is one.\n", 'id': 31, 'uri': ''},
    // {'text': "Yo mama's so ugly, she made a blind kid cry.\n", 'id': 32, 'uri': ''},
    // {'text': "Yo mama's so ugly, her portraits hang themselves.\n", 'id': 33, 'uri': ''},
    // {'text': "Yo mama's so old, she walked out of a museum and the alarm went off.\n", 'id': 34, 'uri': ''},
    // {'text': "Yo mama's teeth are so yellow when she smiles at traffic, it slows down.\n", 'id': 35, 'uri': ''},
    // {'text': "Yo mama's armpits are so hairy, it looks like she's got Buckwheat in a headlock.\n", 'id': 36, 'uri': ''},
    // {'text': "Yo mama's so ugly, when she was little, she had to trick-or-treat by phone.\n", 'id': 37, 'uri': ''},
    // {'text': "Yo mama's so ugly, her birth certificate is an apology letter.\n", 'id': 38, 'uri': ''},
    // {'text': "Yo mama's so ugly, she looked out the window and was arrested for mooning.\n", 'id': 39, 'uri': ''},
    // {'text': "Yo mama's so poor, the ducks throw bread at her.\n", 'id': 40, 'uri': ''},
    // {'text': "Yo mama's so poor, she chases the garbage truck with a grocery list.\n", 'id': 41, 'uri': ''},
    // {'text': "Yo mama's cooking so nasty, she flys got together and fixed the hole in the window screen.\n", 'id': 42, 'uri': ''},
    // {'text': "Yo mama's so depressing, blues singers come to visit her when they've got writer's block.\n", 'id': 43, 'uri': ''},
    // {'text': "Yo mama's so short, you can see her feet on her driver's license.\n", 'id': 44, 'uri': ''},
    // {'text': "Yo mama's so poor, she can't even afford to pay attention.\n", 'id': 45, 'uri': ''},
    // {'text': 'Yo mama so big, her belt size is "equator."\n', 'id': 46, 'uri': ''},
    // {'text': "Yo mama's so classless, she's a Marxist utopia.\n", 'id': 47, 'uri': ''},
    // {'text': 'Yo mama so short, she went to see Santa and he told her to get back to work.\n', 'id': 48, 'uri': ''},
    // {'text': 'Yo mama so scary, the government moved Halloween to her birthday.\n', 'id': 49, 'uri': ''},
    // {'text': "Yo mama's so nasty, they used to call them jumpolines 'til yo mama bounced on one.\n", 'id': 50, 'uri': ''},
    // {'text': "Yo mama's teeth so yellow, I can't believe it's not butter.\n", 'id': 51, 'uri': ''},
    // {'text': "Yo mama's so poor, Nigerian princes wire her money.\n", 'id': 52, 'uri': ''},
    // {'text': 'Yo mama so dumb, she went to the eye doctor to get an iPhone.\n', 'id': 53, 'uri': ''},
    // {'text': "Yo mama's so lazy, she stuck her nose out the window and let the wind blow it.", 'id': 54, 'uri': ''}
  ]